# render.yaml (na raiz do seu repositório PDF Estudo/)

services:
  # --- SERVIÇO BACKEND (já configurado) ---
  - type: web
    name: quiz-backend-api
    runtime: docker
    rootDir: backend
    plan: free
    dockerfilePath: Dockerfile
    # ... (restante do seu render.yaml para o backend)

  # --- SERVIÇO FRONTEND ---
  - type: web # <--- Tipo de serviço: web (para HTTP/HTTPS)
    name: quiz-frontend-app # <--- Indentado 2 espaços em relação ao '- type:'
    runtime: static # <--- Indentado 2 espaços em relação ao '- type:'
    rootDir: frontend # <--- Indentado 2 espaços em relação ao '- type:'
    staticPublishPath: ./build
    # buildOutputDirectory: .
    # publishPath: /
