# render.yaml (na raiz do seu repositório PDF Estudo/)

services:
  - type: web
    name: quiz-backend-api
    env: java
    rootDir: backend
    buildCommand: ./mvnw clean install -DskipTests
    startCommand: java -jar target/quiz-backend-0.0.1-SNAPSHOT.jar # ATENÇÃO: VERIFIQUE E AJUSTE O NOME DO SEU ARQUIVO JAR AQUI!
    envVars:
      - key: JAVA_HOME
        value: /opt/jdk/openjdk