# render.yaml (na raiz do seu repositório PDF Estudo/)

services:
  - type: web
    name: quiz-backend-api
    runtime: docker
    rootDir: backend
    plan: free
    dockerfilePath: Dockerfile # <--- MUDANÇA AQUI: Removido 'backend/'
    # buildCommand e startCommand NÃO SÃO NECESSÁRIOS aqui, pois o Dockerfile os gerencia
    # envVars:
    #   - key: GEMINI_API_KEY # Se já configurou no painel do Render, não precisa aqui.
    #     sync: false