# render.yaml (na raiz do seu repositório PDF Estudo/)

services:
  - type: web
    name: quiz-backend-api
    runtime: docker
    rootDir: backend
    plan: free # <--- ADICIONE ESTA LINHA AQUI
    dockerfilePath: backend/Dockerfile
    # ... (restante do seu render.yaml)