# render.yaml (na raiz do seu repositório PDF Estudo/)

services:
  # --- SERVIÇO BACKEND (já configurado) ---
  - type: web
    name: quiz-backend-api
    runtime: docker
    rootDir: backend
    plan: free
    dockerfilePath: Dockerfile
    # ... (restante do seu render.yaml para o backend)

  # --- NOVO SERVIÇO FRONTEND ---
  - type: static # Tipo de serviço para arquivos estáticos (HTML, CSS, JS)
    name: quiz-frontend-app # Um nome para seu serviço de frontend
    rootDir: frontend      # Supondo que seus arquivos frontend estão na pasta 'frontend/'
    buildOutputDirectory: . # Onde os arquivos estáticos compilados (se houver) serão encontrados. Para HTML/CSS/JS puro, é a raiz.