# render.yaml (na raiz do seu repositório PDF Estudo/)

services:
  # --- SERVIÇO BACKEND (já configurado) ---
  - type: web
    name: quiz-backend-api
    runtime: docker
    rootDir: backend
    plan: free
    dockerfilePath: Dockerfile
    # ... (restante do seu render.yaml para o backend)